spring.application.name=novely-peak-api

# Habilitação de Virtual Threads (Java 21)
spring.threads.virtual.enabled=true

# Configurações do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5434/novely_peak_db
spring.datasource.username=novely_admin
spring.datasource.password=peak_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Flyway
spring.flyway.baseline-on-migrate=true