

ALTER TABLE tasks ADD COLUMN links VARCHAR(255)[] DEFAULT '{}' NOT NULL;

CREATE TABLE subtasks (
    id UUID PRIMARY KEY,
    task_id UUID NOT NULL,
    title VARCHAR(150) NOT NULL,
    done BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subtasks_task FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE
)